### ISSUE TITLE
Drop requirement of ext-mongo

### ISSUE THREAD

**Issue by pascaldevink** [broadway/broadway-saga#13]
In commit https://github.com/broadway/broadway-saga/commit/2a876bf2cd4771f74f9751383e3b998eaa957654, ext-mongo is suddenly a hard system requirement. There is no notice about it in the release notes (or in the commit itself).
This is the relevant part in composer.json:
```
"config": {
    "platform": {
      "ext-mongo": "1.6.16"
    }
  }
```

I think it makes no sense to always have this hard requirement if the sagas are in-memory (which we have) and never use mongo (which we don't).

Upgrading is now blocked for everybody who doesn't use mongodb at all.

Could this be fixed, or is mongodb going to be required going forward?

**Comment by othillo** [comment]
I'm sorry to hear that. Indeed it's broken for in-memory users like yourself.
The ext-mongo dependency being optional (at least as it is intended) causes too many problems IMO. I think I'm going to split the mongo stuff to a separate repo (making this repo in-memory only). (This helps upgrading from ext-mongo to ext-mongodb as well (https://github.com/broadway/broadway-saga/issues/11)).
