### ISSUE TITLE
Scenario requires MultipleSagaManager instead of SagaManagerInterface

### ISSUE THREAD

**Issue by jaco** [broadway/broadway-saga#46]
`Scenario` requires `MultipleSagaManager` instead of `SagaManagerInterface`. 

Is there reason for that? I see only `handle()` usage in `Scenario`.

In my opinion `Scenario` should not depend on any specific `SagaManager` implementation.

**Comment by othillo** [comment]
The `Scenario` is our (opinionated) implementation of a test helper to be instantiated by an implementation of `SagaScenarioTestCase`. Because `MultipleSagaManager` is the only implementation of `SagaManagerInterface` we use that.

**Comment by othillo** [comment]
Maybe we should extract the `createScenario` method from the `SagaScenarioTestCase` and name it `MultipleSageScenarioTestCase`. Would make sense if we create a `SimpleSagaManager` next to the `MultipleSagaManager`.

**Comment by jaco** [comment]
I totally understand why you use `MultipleSagaManager` implementation in tests :) I just don't understand why test scenario must depend on particular SagaManager. 

It will be nice to overload `createScenario()` in order to use own managers (in my case, more complicated saga state logic). In fact I did just that and with that only change (`MultipleSagaManager` => `SagaManagerInterface` in `Scenario` constructor) it works perfectly.
