### ISSUE TITLE
ramsey/uuid always needed?

### ISSUE THREAD

**Issue by Nikoms** [broadway/broadway-saga#6]
Hello,

I installed this lib, and I juste wondering if "ramsey/uuid" is required (not only on "dev"). I see that the "StateManager" uses "UuidGeneratorInterface" which is "Version4Generator" by default (in symfony bundle)

If I'm wrong, please ignore this message :)

**Comment by othillo** [comment]
Hi, for broadway-saga, "ramsey/uuid" is not required but recommended.
As an alternative you can implement the https://github.com/broadway/broadway-uuid-generator/blob/master/src/Broadway/UuidGenerator/UuidGeneratorInterface.php
